project:
  type: website
  output-dir: _site
  resources:
    - "content/slides/css/**"
    - "content/slides/images/**"
    - "content/slides/r-scripts/**"
  render:
    - "*.qmd"
    - "content/**/*.qmd"
    - "!.claude/**"
    - "!CLAUDE.md"

lang: pt

publish:
  method: gh-pages
  repo: FCopf/prob-est-2026

website:
  page-navigation: true
  title: "5290 - PROBABILIDADE E ESTATÍSTICA"
  description: "Materiais, cronograma e recursos da UC Probabilidade e Estatística do Bict Mar - Unifesp."
  site-url: "https://fcopf.github.io/prob-est-2026"

  repo-url: "https://github.com/FCopf/prob-est-2026"
  open-graph: true

  page-footer:
    right: "BACHARELADO INTERDISCIPLINAR EM CIÊNCIA E TECNOLOGIA DO MAR - Bict Mar - Unifesp"
    left: Probabilidade e Estatística - PE
    background: "#296354"

  navbar:
    background: "#3b8170"
    logo: "images/logo.png"
    search: true
    left:
      - text: "Identificação da UC"
        href: course-info/uc-id.qmd
      - text: "Plano de Ensino"
        href: course-info/syllabus.qmd
      - text: "Cronograma"
        href: index.qmd
      - text: "Moodle Graduação"
        href: "https://moodlegrad.unifesp.br/"
        target: "_blank"
    tools:
      - icon: github
        href: https://github.com/FCopf/prob-est-2026
        text: GitHub da UC
        target: "_blank"
      - icon: terminal
        href: https://colab.research.google.com/drive/
        text: Google Colab
        target: "_blank"


# Global format configuration
format:
  html:
    theme:
      light: [cosmo, styles/theme.scss]
      dark: [cosmo, styles/theme-dark.scss]
    toc: true
    number-sections: true
    code-copy: true
    code-overflow: wrap

# Configura projeto para ser executado apenas localmente
execute:
  freeze: auto

bibliography: references.bib